### ISSUE TITLE
Stuck on "warming up filesystem"

### ISSUE THREAD

**Issue by therealjeffg** [fission-suite/dashboard#18]
# Summary

I authenticate but than can't seem to get to the dashboard itself. If I look at Firefox's error console I get:

"asm.js type error: expecting argument type declaration for 't' of the form 'arg = arg|0' or 'arg = +arg' or 'arg = fround(arg)'"

![Screen Shot 2021-05-25 at 1 28 28 PM](https://user-images.githubusercontent.com/104315/119564000-195c0000-bd5d-11eb-8a5a-8c901fe340f5.png)

**Comment by matheus23** [comment]
Related issue: https://github.com/fission-suite/webnative/issues/207

---

The authentication flow was changed in a newer version of webnative.
With the new authentication flow, these errors shouldn't happen anymore.
I've now flipped the switch and deployed the new version of the dashboard to production.
